//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("QuanLySinhVienModel", "FK_KetQua_MonHoc", "MonHoc", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SinhVienEF.MonHoc), "KetQua", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SinhVienEF.KetQua), true)]
[assembly: EdmRelationshipAttribute("QuanLySinhVienModel", "FK_KetQua_SinhVien", "SinhVien", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SinhVienEF.SinhVien), "KetQua", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SinhVienEF.KetQua), true)]
[assembly: EdmRelationshipAttribute("QuanLySinhVienModel", "FK_Lop_Khoa", "Khoa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SinhVienEF.Khoa), "Lop", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SinhVienEF.Lop), true)]
[assembly: EdmRelationshipAttribute("QuanLySinhVienModel", "FK_SinhVien_Lop", "Lop", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SinhVienEF.Lop), "SinhVien", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SinhVienEF.SinhVien), true)]

#endregion

namespace SinhVienEF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class QuanLySinhVienEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new QuanLySinhVienEntities1 object using the connection string found in the 'QuanLySinhVienEntities1' section of the application configuration file.
        /// </summary>
        public QuanLySinhVienEntities1() : base("name=QuanLySinhVienEntities1", "QuanLySinhVienEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLySinhVienEntities1 object.
        /// </summary>
        public QuanLySinhVienEntities1(string connectionString) : base(connectionString, "QuanLySinhVienEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new QuanLySinhVienEntities1 object.
        /// </summary>
        public QuanLySinhVienEntities1(EntityConnection connection) : base(connection, "QuanLySinhVienEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<KetQua> KetQuas
        {
            get
            {
                if ((_KetQuas == null))
                {
                    _KetQuas = base.CreateObjectSet<KetQua>("KetQuas");
                }
                return _KetQuas;
            }
        }
        private ObjectSet<KetQua> _KetQuas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Khoa> Khoas
        {
            get
            {
                if ((_Khoas == null))
                {
                    _Khoas = base.CreateObjectSet<Khoa>("Khoas");
                }
                return _Khoas;
            }
        }
        private ObjectSet<Khoa> _Khoas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lop> Lops
        {
            get
            {
                if ((_Lops == null))
                {
                    _Lops = base.CreateObjectSet<Lop>("Lops");
                }
                return _Lops;
            }
        }
        private ObjectSet<Lop> _Lops;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MonHoc> MonHocs
        {
            get
            {
                if ((_MonHocs == null))
                {
                    _MonHocs = base.CreateObjectSet<MonHoc>("MonHocs");
                }
                return _MonHocs;
            }
        }
        private ObjectSet<MonHoc> _MonHocs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<QuanLyNguoiDung> QuanLyNguoiDungs
        {
            get
            {
                if ((_QuanLyNguoiDungs == null))
                {
                    _QuanLyNguoiDungs = base.CreateObjectSet<QuanLyNguoiDung>("QuanLyNguoiDungs");
                }
                return _QuanLyNguoiDungs;
            }
        }
        private ObjectSet<QuanLyNguoiDung> _QuanLyNguoiDungs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SinhVien> SinhViens
        {
            get
            {
                if ((_SinhViens == null))
                {
                    _SinhViens = base.CreateObjectSet<SinhVien>("SinhViens");
                }
                return _SinhViens;
            }
        }
        private ObjectSet<SinhVien> _SinhViens;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the KetQuas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKetQuas(KetQua ketQua)
        {
            base.AddObject("KetQuas", ketQua);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Khoas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKhoas(Khoa khoa)
        {
            base.AddObject("Khoas", khoa);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lops EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLops(Lop lop)
        {
            base.AddObject("Lops", lop);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MonHocs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMonHocs(MonHoc monHoc)
        {
            base.AddObject("MonHocs", monHoc);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the QuanLyNguoiDungs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQuanLyNguoiDungs(QuanLyNguoiDung quanLyNguoiDung)
        {
            base.AddObject("QuanLyNguoiDungs", quanLyNguoiDung);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SinhViens EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSinhViens(SinhVien sinhVien)
        {
            base.AddObject("SinhViens", sinhVien);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="KetQua")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class KetQua : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new KetQua object.
        /// </summary>
        /// <param name="iD_MonHoc">Initial value of the ID_MonHoc property.</param>
        /// <param name="iD_SinhVien">Initial value of the ID_SinhVien property.</param>
        /// <param name="lanThi">Initial value of the LanThi property.</param>
        /// <param name="diemThi">Initial value of the DiemThi property.</param>
        /// <param name="diemTongKet">Initial value of the DiemTongKet property.</param>
        public static KetQua CreateKetQua(global::System.String iD_MonHoc, global::System.String iD_SinhVien, global::System.Int32 lanThi, global::System.Double diemThi, global::System.Double diemTongKet)
        {
            KetQua ketQua = new KetQua();
            ketQua.ID_MonHoc = iD_MonHoc;
            ketQua.ID_SinhVien = iD_SinhVien;
            ketQua.LanThi = lanThi;
            ketQua.DiemThi = diemThi;
            ketQua.DiemTongKet = diemTongKet;
            return ketQua;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_MonHoc
        {
            get
            {
                return _ID_MonHoc;
            }
            set
            {
                if (_ID_MonHoc != value)
                {
                    OnID_MonHocChanging(value);
                    ReportPropertyChanging("ID_MonHoc");
                    _ID_MonHoc = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_MonHoc");
                    OnID_MonHocChanged();
                }
            }
        }
        private global::System.String _ID_MonHoc;
        partial void OnID_MonHocChanging(global::System.String value);
        partial void OnID_MonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_SinhVien
        {
            get
            {
                return _ID_SinhVien;
            }
            set
            {
                if (_ID_SinhVien != value)
                {
                    OnID_SinhVienChanging(value);
                    ReportPropertyChanging("ID_SinhVien");
                    _ID_SinhVien = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_SinhVien");
                    OnID_SinhVienChanged();
                }
            }
        }
        private global::System.String _ID_SinhVien;
        partial void OnID_SinhVienChanging(global::System.String value);
        partial void OnID_SinhVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanThi
        {
            get
            {
                return _LanThi;
            }
            set
            {
                if (_LanThi != value)
                {
                    OnLanThiChanging(value);
                    ReportPropertyChanging("LanThi");
                    _LanThi = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LanThi");
                    OnLanThiChanged();
                }
            }
        }
        private global::System.Int32 _LanThi;
        partial void OnLanThiChanging(global::System.Int32 value);
        partial void OnLanThiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DiemThi
        {
            get
            {
                return _DiemThi;
            }
            set
            {
                OnDiemThiChanging(value);
                ReportPropertyChanging("DiemThi");
                _DiemThi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiemThi");
                OnDiemThiChanged();
            }
        }
        private global::System.Double _DiemThi;
        partial void OnDiemThiChanging(global::System.Double value);
        partial void OnDiemThiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double DiemTongKet
        {
            get
            {
                return _DiemTongKet;
            }
            set
            {
                OnDiemTongKetChanging(value);
                ReportPropertyChanging("DiemTongKet");
                _DiemTongKet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiemTongKet");
                OnDiemTongKetChanged();
            }
        }
        private global::System.Double _DiemTongKet;
        partial void OnDiemTongKetChanging(global::System.Double value);
        partial void OnDiemTongKetChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_KetQua_MonHoc", "MonHoc")]
        public MonHoc MonHoc
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QuanLySinhVienModel.FK_KetQua_MonHoc", "MonHoc").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QuanLySinhVienModel.FK_KetQua_MonHoc", "MonHoc").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MonHoc> MonHocReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MonHoc>("QuanLySinhVienModel.FK_KetQua_MonHoc", "MonHoc");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MonHoc>("QuanLySinhVienModel.FK_KetQua_MonHoc", "MonHoc", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_KetQua_SinhVien", "SinhVien")]
        public SinhVien SinhVien
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SinhVien>("QuanLySinhVienModel.FK_KetQua_SinhVien", "SinhVien").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SinhVien>("QuanLySinhVienModel.FK_KetQua_SinhVien", "SinhVien").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SinhVien> SinhVienReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SinhVien>("QuanLySinhVienModel.FK_KetQua_SinhVien", "SinhVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SinhVien>("QuanLySinhVienModel.FK_KetQua_SinhVien", "SinhVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="Khoa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Khoa : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Khoa object.
        /// </summary>
        /// <param name="khoa_ID">Initial value of the Khoa_ID property.</param>
        /// <param name="tenKhoa">Initial value of the TenKhoa property.</param>
        public static Khoa CreateKhoa(global::System.String khoa_ID, global::System.String tenKhoa)
        {
            Khoa khoa = new Khoa();
            khoa.Khoa_ID = khoa_ID;
            khoa.TenKhoa = tenKhoa;
            return khoa;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Khoa_ID
        {
            get
            {
                return _Khoa_ID;
            }
            set
            {
                if (_Khoa_ID != value)
                {
                    OnKhoa_IDChanging(value);
                    ReportPropertyChanging("Khoa_ID");
                    _Khoa_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Khoa_ID");
                    OnKhoa_IDChanged();
                }
            }
        }
        private global::System.String _Khoa_ID;
        partial void OnKhoa_IDChanging(global::System.String value);
        partial void OnKhoa_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenKhoa
        {
            get
            {
                return _TenKhoa;
            }
            set
            {
                OnTenKhoaChanging(value);
                ReportPropertyChanging("TenKhoa");
                _TenKhoa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenKhoa");
                OnTenKhoaChanged();
            }
        }
        private global::System.String _TenKhoa;
        partial void OnTenKhoaChanging(global::System.String value);
        partial void OnTenKhoaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_Lop_Khoa", "Lop")]
        public EntityCollection<Lop> Lops
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Lop>("QuanLySinhVienModel.FK_Lop_Khoa", "Lop");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Lop>("QuanLySinhVienModel.FK_Lop_Khoa", "Lop", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="Lop")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lop : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lop object.
        /// </summary>
        /// <param name="lop_ID">Initial value of the Lop_ID property.</param>
        /// <param name="tenLop">Initial value of the TenLop property.</param>
        /// <param name="iD_Khoa">Initial value of the ID_Khoa property.</param>
        public static Lop CreateLop(global::System.String lop_ID, global::System.String tenLop, global::System.String iD_Khoa)
        {
            Lop lop = new Lop();
            lop.Lop_ID = lop_ID;
            lop.TenLop = tenLop;
            lop.ID_Khoa = iD_Khoa;
            return lop;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Lop_ID
        {
            get
            {
                return _Lop_ID;
            }
            set
            {
                if (_Lop_ID != value)
                {
                    OnLop_IDChanging(value);
                    ReportPropertyChanging("Lop_ID");
                    _Lop_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Lop_ID");
                    OnLop_IDChanged();
                }
            }
        }
        private global::System.String _Lop_ID;
        partial void OnLop_IDChanging(global::System.String value);
        partial void OnLop_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenLop
        {
            get
            {
                return _TenLop;
            }
            set
            {
                OnTenLopChanging(value);
                ReportPropertyChanging("TenLop");
                _TenLop = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenLop");
                OnTenLopChanged();
            }
        }
        private global::System.String _TenLop;
        partial void OnTenLopChanging(global::System.String value);
        partial void OnTenLopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Khoa
        {
            get
            {
                return _ID_Khoa;
            }
            set
            {
                OnID_KhoaChanging(value);
                ReportPropertyChanging("ID_Khoa");
                _ID_Khoa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_Khoa");
                OnID_KhoaChanged();
            }
        }
        private global::System.String _ID_Khoa;
        partial void OnID_KhoaChanging(global::System.String value);
        partial void OnID_KhoaChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_Lop_Khoa", "Khoa")]
        public Khoa Khoa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QuanLySinhVienModel.FK_Lop_Khoa", "Khoa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QuanLySinhVienModel.FK_Lop_Khoa", "Khoa").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Khoa> KhoaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Khoa>("QuanLySinhVienModel.FK_Lop_Khoa", "Khoa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Khoa>("QuanLySinhVienModel.FK_Lop_Khoa", "Khoa", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_SinhVien_Lop", "SinhVien")]
        public EntityCollection<SinhVien> SinhViens
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SinhVien>("QuanLySinhVienModel.FK_SinhVien_Lop", "SinhVien");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SinhVien>("QuanLySinhVienModel.FK_SinhVien_Lop", "SinhVien", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="MonHoc")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MonHoc : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MonHoc object.
        /// </summary>
        /// <param name="monHoc_ID">Initial value of the MonHoc_ID property.</param>
        /// <param name="tenMonHoc">Initial value of the TenMonHoc property.</param>
        /// <param name="soTrinh">Initial value of the SoTrinh property.</param>
        /// <param name="giangVien">Initial value of the GiangVien property.</param>
        public static MonHoc CreateMonHoc(global::System.String monHoc_ID, global::System.String tenMonHoc, global::System.Int32 soTrinh, global::System.String giangVien)
        {
            MonHoc monHoc = new MonHoc();
            monHoc.MonHoc_ID = monHoc_ID;
            monHoc.TenMonHoc = tenMonHoc;
            monHoc.SoTrinh = soTrinh;
            monHoc.GiangVien = giangVien;
            return monHoc;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MonHoc_ID
        {
            get
            {
                return _MonHoc_ID;
            }
            set
            {
                if (_MonHoc_ID != value)
                {
                    OnMonHoc_IDChanging(value);
                    ReportPropertyChanging("MonHoc_ID");
                    _MonHoc_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("MonHoc_ID");
                    OnMonHoc_IDChanged();
                }
            }
        }
        private global::System.String _MonHoc_ID;
        partial void OnMonHoc_IDChanging(global::System.String value);
        partial void OnMonHoc_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenMonHoc
        {
            get
            {
                return _TenMonHoc;
            }
            set
            {
                OnTenMonHocChanging(value);
                ReportPropertyChanging("TenMonHoc");
                _TenMonHoc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenMonHoc");
                OnTenMonHocChanged();
            }
        }
        private global::System.String _TenMonHoc;
        partial void OnTenMonHocChanging(global::System.String value);
        partial void OnTenMonHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SoTrinh
        {
            get
            {
                return _SoTrinh;
            }
            set
            {
                OnSoTrinhChanging(value);
                ReportPropertyChanging("SoTrinh");
                _SoTrinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SoTrinh");
                OnSoTrinhChanged();
            }
        }
        private global::System.Int32 _SoTrinh;
        partial void OnSoTrinhChanging(global::System.Int32 value);
        partial void OnSoTrinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GiangVien
        {
            get
            {
                return _GiangVien;
            }
            set
            {
                OnGiangVienChanging(value);
                ReportPropertyChanging("GiangVien");
                _GiangVien = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GiangVien");
                OnGiangVienChanged();
            }
        }
        private global::System.String _GiangVien;
        partial void OnGiangVienChanging(global::System.String value);
        partial void OnGiangVienChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_KetQua_MonHoc", "KetQua")]
        public EntityCollection<KetQua> KetQuas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KetQua>("QuanLySinhVienModel.FK_KetQua_MonHoc", "KetQua");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KetQua>("QuanLySinhVienModel.FK_KetQua_MonHoc", "KetQua", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="QuanLyNguoiDung")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class QuanLyNguoiDung : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new QuanLyNguoiDung object.
        /// </summary>
        /// <param name="tenDangNhap">Initial value of the TenDangNhap property.</param>
        /// <param name="matKhau">Initial value of the MatKhau property.</param>
        public static QuanLyNguoiDung CreateQuanLyNguoiDung(global::System.String tenDangNhap, global::System.String matKhau)
        {
            QuanLyNguoiDung quanLyNguoiDung = new QuanLyNguoiDung();
            quanLyNguoiDung.TenDangNhap = tenDangNhap;
            quanLyNguoiDung.MatKhau = matKhau;
            return quanLyNguoiDung;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenDangNhap
        {
            get
            {
                return _TenDangNhap;
            }
            set
            {
                if (_TenDangNhap != value)
                {
                    OnTenDangNhapChanging(value);
                    ReportPropertyChanging("TenDangNhap");
                    _TenDangNhap = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TenDangNhap");
                    OnTenDangNhapChanged();
                }
            }
        }
        private global::System.String _TenDangNhap;
        partial void OnTenDangNhapChanging(global::System.String value);
        partial void OnTenDangNhapChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MatKhau
        {
            get
            {
                return _MatKhau;
            }
            set
            {
                OnMatKhauChanging(value);
                ReportPropertyChanging("MatKhau");
                _MatKhau = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MatKhau");
                OnMatKhauChanged();
            }
        }
        private global::System.String _MatKhau;
        partial void OnMatKhauChanging(global::System.String value);
        partial void OnMatKhauChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HoTen
        {
            get
            {
                return _HoTen;
            }
            set
            {
                OnHoTenChanging(value);
                ReportPropertyChanging("HoTen");
                _HoTen = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HoTen");
                OnHoTenChanged();
            }
        }
        private global::System.String _HoTen;
        partial void OnHoTenChanging(global::System.String value);
        partial void OnHoTenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DienThoai
        {
            get
            {
                return _DienThoai;
            }
            set
            {
                OnDienThoaiChanging(value);
                ReportPropertyChanging("DienThoai");
                _DienThoai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DienThoai");
                OnDienThoaiChanged();
            }
        }
        private global::System.String _DienThoai;
        partial void OnDienThoaiChanging(global::System.String value);
        partial void OnDienThoaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DiaChi
        {
            get
            {
                return _DiaChi;
            }
            set
            {
                OnDiaChiChanging(value);
                ReportPropertyChanging("DiaChi");
                _DiaChi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DiaChi");
                OnDiaChiChanged();
            }
        }
        private global::System.String _DiaChi;
        partial void OnDiaChiChanging(global::System.String value);
        partial void OnDiaChiChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="SinhVien")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SinhVien : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SinhVien object.
        /// </summary>
        /// <param name="sinhVien_ID">Initial value of the SinhVien_ID property.</param>
        /// <param name="tenSinhVien">Initial value of the TenSinhVien property.</param>
        /// <param name="gioiTinh">Initial value of the GioiTinh property.</param>
        /// <param name="ngaySinh">Initial value of the NgaySinh property.</param>
        /// <param name="noiSinh">Initial value of the NoiSinh property.</param>
        /// <param name="khoaHoc">Initial value of the KhoaHoc property.</param>
        /// <param name="lyLich">Initial value of the LyLich property.</param>
        /// <param name="iD_Lop">Initial value of the ID_Lop property.</param>
        public static SinhVien CreateSinhVien(global::System.String sinhVien_ID, global::System.String tenSinhVien, global::System.Byte gioiTinh, global::System.DateTime ngaySinh, global::System.String noiSinh, global::System.String khoaHoc, global::System.String lyLich, global::System.String iD_Lop)
        {
            SinhVien sinhVien = new SinhVien();
            sinhVien.SinhVien_ID = sinhVien_ID;
            sinhVien.TenSinhVien = tenSinhVien;
            sinhVien.GioiTinh = gioiTinh;
            sinhVien.NgaySinh = ngaySinh;
            sinhVien.NoiSinh = noiSinh;
            sinhVien.KhoaHoc = khoaHoc;
            sinhVien.LyLich = lyLich;
            sinhVien.ID_Lop = iD_Lop;
            return sinhVien;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SinhVien_ID
        {
            get
            {
                return _SinhVien_ID;
            }
            set
            {
                if (_SinhVien_ID != value)
                {
                    OnSinhVien_IDChanging(value);
                    ReportPropertyChanging("SinhVien_ID");
                    _SinhVien_ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("SinhVien_ID");
                    OnSinhVien_IDChanged();
                }
            }
        }
        private global::System.String _SinhVien_ID;
        partial void OnSinhVien_IDChanging(global::System.String value);
        partial void OnSinhVien_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TenSinhVien
        {
            get
            {
                return _TenSinhVien;
            }
            set
            {
                OnTenSinhVienChanging(value);
                ReportPropertyChanging("TenSinhVien");
                _TenSinhVien = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TenSinhVien");
                OnTenSinhVienChanged();
            }
        }
        private global::System.String _TenSinhVien;
        partial void OnTenSinhVienChanging(global::System.String value);
        partial void OnTenSinhVienChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte GioiTinh
        {
            get
            {
                return _GioiTinh;
            }
            set
            {
                OnGioiTinhChanging(value);
                ReportPropertyChanging("GioiTinh");
                _GioiTinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GioiTinh");
                OnGioiTinhChanged();
            }
        }
        private global::System.Byte _GioiTinh;
        partial void OnGioiTinhChanging(global::System.Byte value);
        partial void OnGioiTinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime NgaySinh
        {
            get
            {
                return _NgaySinh;
            }
            set
            {
                OnNgaySinhChanging(value);
                ReportPropertyChanging("NgaySinh");
                _NgaySinh = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NgaySinh");
                OnNgaySinhChanged();
            }
        }
        private global::System.DateTime _NgaySinh;
        partial void OnNgaySinhChanging(global::System.DateTime value);
        partial void OnNgaySinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NoiSinh
        {
            get
            {
                return _NoiSinh;
            }
            set
            {
                OnNoiSinhChanging(value);
                ReportPropertyChanging("NoiSinh");
                _NoiSinh = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NoiSinh");
                OnNoiSinhChanged();
            }
        }
        private global::System.String _NoiSinh;
        partial void OnNoiSinhChanging(global::System.String value);
        partial void OnNoiSinhChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoiOHienTai
        {
            get
            {
                return _NoiOHienTai;
            }
            set
            {
                OnNoiOHienTaiChanging(value);
                ReportPropertyChanging("NoiOHienTai");
                _NoiOHienTai = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoiOHienTai");
                OnNoiOHienTaiChanged();
            }
        }
        private global::System.String _NoiOHienTai;
        partial void OnNoiOHienTaiChanging(global::System.String value);
        partial void OnNoiOHienTaiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String KhoaHoc
        {
            get
            {
                return _KhoaHoc;
            }
            set
            {
                OnKhoaHocChanging(value);
                ReportPropertyChanging("KhoaHoc");
                _KhoaHoc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("KhoaHoc");
                OnKhoaHocChanged();
            }
        }
        private global::System.String _KhoaHoc;
        partial void OnKhoaHocChanging(global::System.String value);
        partial void OnKhoaHocChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LyLich
        {
            get
            {
                return _LyLich;
            }
            set
            {
                OnLyLichChanging(value);
                ReportPropertyChanging("LyLich");
                _LyLich = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LyLich");
                OnLyLichChanged();
            }
        }
        private global::System.String _LyLich;
        partial void OnLyLichChanging(global::System.String value);
        partial void OnLyLichChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Lop
        {
            get
            {
                return _ID_Lop;
            }
            set
            {
                OnID_LopChanging(value);
                ReportPropertyChanging("ID_Lop");
                _ID_Lop = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ID_Lop");
                OnID_LopChanged();
            }
        }
        private global::System.String _ID_Lop;
        partial void OnID_LopChanging(global::System.String value);
        partial void OnID_LopChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HinhAnh
        {
            get
            {
                return _HinhAnh;
            }
            set
            {
                OnHinhAnhChanging(value);
                ReportPropertyChanging("HinhAnh");
                _HinhAnh = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HinhAnh");
                OnHinhAnhChanged();
            }
        }
        private global::System.String _HinhAnh;
        partial void OnHinhAnhChanging(global::System.String value);
        partial void OnHinhAnhChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_KetQua_SinhVien", "KetQua")]
        public EntityCollection<KetQua> KetQuas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<KetQua>("QuanLySinhVienModel.FK_KetQua_SinhVien", "KetQua");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<KetQua>("QuanLySinhVienModel.FK_KetQua_SinhVien", "KetQua", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("QuanLySinhVienModel", "FK_SinhVien_Lop", "Lop")]
        public Lop Lop
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lop>("QuanLySinhVienModel.FK_SinhVien_Lop", "Lop").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lop>("QuanLySinhVienModel.FK_SinhVien_Lop", "Lop").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lop> LopReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lop>("QuanLySinhVienModel.FK_SinhVien_Lop", "Lop");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lop>("QuanLySinhVienModel.FK_SinhVien_Lop", "Lop", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="QuanLySinhVienModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
